# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.0
jobs:
  build:
    working_directory: ~/kioshi/server
    docker:
      - image: circleci/node:8.11.4
    steps:
      - checkout:
          path: ~/kioshi
      - run:
          name: Update npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum 'package.json'}}
      - run:
          name: Install package dependency
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum 'package.json'}}
          paths:
            - node_modules
  test:
    working_directory: ~/kioshi/server
    docker:
      - image: circleci/node:8.11.4
    steps:
      - checkout:
          path: ~/kioshi
      - run:
          name: Test
          command: npm test
      - store_artifacts:
          path: index.html
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
