apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-app
spec:
  selector:
    matchLabels:
      app: {{.Release.Name}}-kioshi
  replicas: {{.Values.api.replicas}}
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-kioshi
    spec:
      containers:
        - name: kioshi
          image: ffoysal/kioshi:{{.Values.api.imageTag}}
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: "mongodb://{{.Release.Name}}-mongo:27017/mms-db"

---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-api
spec:
  selector:
    app: {{.Release.Name}}-kioshi
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
  type: LoadBalancer
