# DB deployment object
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-mongo
spec:
  selector:
    matchLabels:
      app: {{.Release.Name}}-mongo
      tier: backend
  replicas: {{.Values.db.replicas}}
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-mongo
        tier: backend
    spec:
      containers:
        - name: mongo
          image: mongo:{{.Values.db.imageTag}}
          ports:
            - name: http
              containerPort: 27017
---
# DB service by which app will reach to db
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-mongo
spec:
  selector:
    app: {{.Release.Name}}-mongo
    tier: backend
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
