swagger: "2.0"
info:
  title: "Message Management Servcie"
  version: "1.0.0"
  description: |
    This RESTFul API provides various methods to manage messages.

tags:
  - name: "message"
    description: "CRUD operations for messages"

paths:
  /messages:
    post:
      tags:
        - "message"
      summary: "Create a new message"
      description: |
        Create a new message and set location header
        /messages/:id where id is generted by the server
      parameters:
        - in: "body"
          name: "body"
          description: |
            A JSON object having only one key called "message"
          required: true
          schema:
            $ref: "#/definitions/MessagePostBody"
      responses:
        201:
          description: "Message successfully created"
        400:
          description: "Missing/invalid body"
        500:
          description: "Failed to handle the request"
    get:
      tags:
        - "message"
      summary: "Return list of messages"
      description: "Return list of message with aditional paging info"
      parameters:
        - in: "query"
          name: "page"
          type: "integer"
          description: "A starting page number, default to 1"
          required: false
        - in: "query"
          name: "limit"
          type: "integer"
          description: "Number of entries per page, default to 3"
          required: false
        - in: "query"
          name: "palindrome"
          type: "boolean"
          description: |
            Additional filter based on whether palindrome or not(true/false),
            No filter applied by default
      responses:
        200:
          description: "Return list of message with paging info"
          schema:
            $ref: "#/definitions/ListMessageResponseBody"
        500:
          description: "Failed to handle the request"

  /messages/{id}:
    get:
      tags:
        - "message"
      summary: "Get details of a message"
      description: "Get details of a particular message"
      parameters:
        - name: "id"
          in: "path"
          description: "the message id"
          type: "string"
          required: true
      responses:
        200:
          description: "The message object is returned in the response body"
          schema:
            $ref: "#/definitions/MessageObject"
        404:
          description: "The requested message with the id not found"
        500:
          description: "Failed to handle the request"
    patch:
      tags:
        - "message"
      summary: "Update the message of the specified id"
      description: "Update the message and the properties of the message"
      parameters:
        - name: "id"
          in: "path"
          description: "the message id"
          type: "string"
          required: true
        - in: "body"
          name: "body"
          description: |
            A JSON object having only one key called message:
          required: true
          schema:
            $ref: "#/definitions/MessagePostBody"
      responses:
        204:
          description: "The specified message has been updated with the supplied body"
        404:
          description: "The specified message not found"
        500:
          description: "Failed to handle the request"
    delete:
      tags:
        - "message"
      summary: "Delete the specified message"
      description: "Delete the specified message"
      parameters:
        - name: "id"
          in: "path"
          description: "the message id"
          type: "string"
          required: true
      responses:
        204:
          description: "The specified message has been deleted"
        404:
          description: "The specified message not found"
        500:
          description: "Failed to handle the request"

definitions:
  MessageObject:
    type: "object"
    properties:
      _id:
        type: "string"
        example: "f91d675d52584db6be3666259a06ebb5"
      message:
        type: "string"
        example: "racecar"
      isPalindrome:
        type: "boolean"
        example: true
      length:
        type: "number"
        example: 6
      createdAt:
        type: "string"
        example: "2019-06-03T04:00:36.105Z"
      lastUpdatedAt:
        type: "string"
        example: "2019-06-03T04:00:36.105Z"

  ListMessageResponseBody:
    type: "object"
    properties:
      messages:
        type: "array"
        items:
          $ref: "#/definitions/MessageObject"
      page:
        type: "number"
        example: 1
      totalPages:
        type: "number"
        example: 10
      totalMessages:
        type: "number"
        example: 10
      hasNextPage:
        type: "boolean"
        example: true

  MessagePostBody:
    type: "object"
    properties:
      message:
        type: "string"
        example: "racecar"
